# *****************************************************************************************
# Project:              CS6150 Lab
# Subtree:              /home/hema/cs6150/2021/labs/lab6
# Filename:             Makefile for Lists
# Programmer:           Hema A Murthy
# Host System:          Linux
# Date Created:         17/Sept/2021
# Project:              Implementation of Lists using Arrays and Linked Lists
# *****************************************************************************************

SRCDIR = ./src
OBJDIR = ./obj
BINDIR = ./bin
INCDIR = ./include
CFLAGS = -g -c -I$(INCDIR)
CC = g++

